name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_dots=#2d333b,#0e4429,#006d32,#26a641,#39d353&color_snake=purple

      - name: Crop progress bar from SVG
        run: |
          sed -i -E 's/viewBox="0 0 ([0-9]+) [0-9]+"/viewBox="0 0 \1 112"/g' dist/*.svg

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
